[package]
name = "unix"
version = "0.1.2"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Interface to Unix system facilities"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/unix/"

[dependencies]
bitflags = "0.7"
i-o = "0.2"
libc = "0.2"
syscall = "0.2"
