[package]
name = "unix"
version = "0.4.2"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Interface to Unix system facilities"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/unix/"

[dependencies]
rm = "0.3.2"
syscall = "0.2"
unix = "0.5"
